---
name: "CI"
on:
  push:
      paths:
      - '.github/workflows/*'
      - '*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.22.1'

      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Run go fmt
        run: make fmt

      - name: Run go vet
        run: make vet

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --snapshot --skip=publish --clean --config .github/config/goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run go lint
      #   uses: golangci/golangci-lint-action@v4
      #   with:
      #     version: v1.57.2
      #     args: --timeout 5m --enable revive,gofmt,exportloopref --exclude-use-default=false --modules-download-mode=vendor --build-tags integration

