---
name: "Release"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.22.1'

      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --config .github/config/goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
